### ISSUE TITLE
Get stuck as soon as it gets into SLAM mode

### ISSUE THREAD

**Issue by XinyuWang2** [834810269/DF-ORB-SLAM#1]

**Comment by 834810269** [comment]
You should run this project with ROS and run the depth recovery node or monodepth node first in [DF-ROS-Node](https://github.com/834810269/DF-ROS-Node)

**Comment by XinyuWang2** [comment]
Oh, thanks a lot. But do you know where I can change to make it run without ROS?

**Comment by XinyuWang2** [comment]
Or can you tell me a bit more about how to run this with ROS? I haven't used it before.

**Comment by 834810269** [comment]
You need to use depth prediction method to predict the depth of your raw images and save depth as CV_32F type and then run RGBD mode of this modified ORB-SLAM without ROS.
If you want to use it with ROS,you can refer to the original ORB-SLAM2 and the ROS wiki.
